# Macro file for the initialization of example B4
# in interactive session
#

/control/execute place_detectors.mac

# Set some default verbose
#
/control/verbose 2
/control/saveHistory
/run/verbose 2
#
# Change the default number of threads (in multi-threaded mode)
#/run/numberOfThreads 4
#
# Initialize kernel
/run/initialize
#/control/execute place_detectors.mac
#
# Visualization setting
/control/execute vis.mac
