# Macro file for example B4
# 
# To be run preferably in batch, without graphics:
# % exampleB4[a,b,c,d] run2.mac
#
#/run/numberOfWorkers 4
/run/initialize
#
# Default kinemtics: 
# electron 50 MeV in direction (0.,0.,1.)
# 1000 events
#
/gps/number 1
/gps/ang/type iso
/gps/ang/mintheta 0 degree
/gps/ang/maxtheta 180 degree
/gps/particle gamma
/gps/energy 1331.92 keV
/run/printProgress 10000
/run/beamOn 100000

