// Build-time host tool: turns an arbitrary binary file into a normal
// compiler-emitted C++ translation unit (const array + companion header).
//
// This replaces the old incbin.h/`.incbin` inline-asm approach, which placed
// its generated symbols in whatever section the assembler happened to be in
// after the raw asm block ran. On GCC/aarch64/ELF that could leave a
// dynamically-initialized global's storage inside the read-only .text
// segment, causing a SIGSEGV on first write. A plain `static const` array
// defined in a real translation unit is placed by the compiler like any
// other global and does not have that failure mode.
//
// Usage: bin2cpp <input-file> <output.cc> <output.hh> <header-guard-macro> <symbol-name>

#include <cstddef>
#include <cstdint>
#include <fstream>
#include <iostream>
#include <vector>

int main(int argc, char **argv)
{
    if (argc != 6) {
        std::cerr << "usage: " << argv[0]
                  << " <input-file> <output.cc> <output.hh> <header-guard-macro> <symbol-name>\n";
        return 1;
    }

    const std::string inputPath = argv[1];
    const std::string outputCc = argv[2];
    const std::string outputHh = argv[3];
    const std::string guard = argv[4];
    const std::string symbol = argv[5];

    std::ifstream in(inputPath, std::ios::binary);
    if (!in) {
        std::cerr << "bin2cpp: cannot open input file '" << inputPath << "'\n";
        return 1;
    }

    std::vector<unsigned char> data((std::istreambuf_iterator<char>(in)),
                                     std::istreambuf_iterator<char>());
    if (in.bad()) {
        std::cerr << "bin2cpp: error reading '" << inputPath << "'\n";
        return 1;
    }

    // Header: declares the array (with a known bound) and the size as a
    // compile-time constant, so consumers never need a runtime read of
    // another translation unit's value.
    {
        std::ofstream hh(outputHh, std::ios::trunc);
        if (!hh) {
            std::cerr << "bin2cpp: cannot open output header '" << outputHh << "'\n";
            return 1;
        }
        hh << "// Generated by bin2cpp from " << inputPath << ". Do not edit.\n"
           << "#ifndef " << guard << "\n"
           << "#define " << guard << "\n\n"
           << "#include <cstddef>\n\n"
           << "extern const unsigned char " << symbol << "_data[" << data.size() << "];\n"
           << "inline constexpr std::size_t " << symbol << "_size = " << data.size() << ";\n\n"
           << "#endif // " << guard << "\n";
    }

    // Source: defines the array contents.
    {
        std::ofstream cc(outputCc, std::ios::trunc);
        if (!cc) {
            std::cerr << "bin2cpp: cannot open output source '" << outputCc << "'\n";
            return 1;
        }
        cc << "// Generated by bin2cpp from " << inputPath << ". Do not edit.\n"
           << "#include \"" << outputHh.substr(outputHh.find_last_of("/\\") + 1) << "\"\n\n"
           << "extern const unsigned char " << symbol << "_data[" << data.size() << "] = {\n";

        cc << std::hex;
        for (std::size_t i = 0; i < data.size(); ++i) {
            if (i % 20 == 0) cc << "    ";
            cc << "0x" << static_cast<unsigned>(data[i]);
            if (i + 1 != data.size()) cc << ",";
            cc << ((i % 20 == 19) ? "\n" : " ");
        }
        cc << std::dec;
        if (data.empty()) cc << "    0\n"; // avoid a zero-size array
        cc << "};\n";
    }

    return 0;
}
