name: MacOS

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  CTEST_OUTPUT_ON_FAILURE: 1
  CPM_SOURCE_CACHE: ${{ github.workspace }}/cpm_modules

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: "**/cpm_modules"
          key: ${{ github.workflow }}-cpm-modules-${{ hashFiles('**/CMakeLists.txt', '**/*.cmake') }}

      - name: Install dependencies
        run: |
          cp external/geant4.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/geant4.rb
          brew install wget cmake assimp geant4

      - name: configure
        run: cmake -Sall -Bbuild -DCMAKE_BUILD_TYPE=Debug

      - name: build
        run: cmake --build build -j4

      - name: run
        run: ./build/app/AFRODITE -m macros/run.mac

      - name: test
        run: |
          cd build
          ctest --build-config Debug