name: MacOS

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  CTEST_OUTPUT_ON_FAILURE: 1
  CPM_SOURCE_CACHE: ${{ github.workspace }}/cpm_modules

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v6

      - name: Update Homebrew
        run: |
          brew tap vetlewi/formula
          brew trust vetlewi/formula
          brew update

      - name: Configure Homebrew cache
        uses: actions/cache@v5
        with:
          path: |
            ~/Library/Cache/Homebrew/geant4--*
            ~/Library/Cache/homebrew/downloads/*--geant4-*
            ~/Library/Cache/Homebrew/downloads/*--G4*
          key: brew-${{ hashFiles('.github/brew-formulae') }}

      - name: Install Homebrew dependencies
        run: brew install geant4

      - uses: actions/cache@v5
        with:
          path: "**/cpm_modules"
          key: ${{ github.workflow }}-cpm-modules-${{ hashFiles('**/CMakeLists.txt', '**/*.cmake') }}

      - name: configure
        run: cmake -Sall -Bbuild -DCMAKE_BUILD_TYPE=Debug

      - name: build
        run: cmake --build build -j4

      - name: test
        run: |
          cd build
          ctest --build-config Debug