name: MacOS

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  CTEST_OUTPUT_ON_FAILURE: 1
  CPM_SOURCE_CACHE: ${{ github.workspace }}/cpm_modules

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: |
            "**/cpm_modules"
            Darwin-clang12.0.0-BigSur.tar.gz
            G4EMLOW.7.13.tar.gz
          key: ${{ github.workflow }}-cpm-modules-${{ hashFiles('**/CMakeLists.txt', '**/*.cmake') }}

      - name: Install dependencies
        run: |
          brew install wget cmake assimp
          if [ ! -f Darwin-clang12.0.0-BigSur.tar.gz ]; then wget http://cern.ch/geant4-data/releases/lib4.10.7.p01/Darwin-clang12.0.0-BigSur.tar.gz fi
          if [ ! -f G4EMLOW.7.13.tar.gz ]; then wget http://cern.ch/geant4-data/datasets/G4EMLOW.7.13.tar.gz fi
          tar xzf Darwin-clang12.0.0-BigSur.tar.gz
          tar xzf G4EMLOW.7.13.tar.gz
          sudo mkdir /opt/local
          sudo mv Geant4-10.7.1-Darwin/bin /opt/local/bin
          sudo mv Geant4-10.7.1-Darwin/include/* /opt/local/include
          sudo mv Geant4-10.7.1-Darwin/lib/* /opt/local/lib
          sudo mv Geant4-10.7.1-Darwin/share/* /opt/local/share
          sudo mv G4EMLOW7.13 /opt/local/share/Geant4-10.7.1/data

      - name: configure
        run: cmake -Sall -Bbuild -DCMAKE_BUILD_TYPE=Debug

      - name: build
        run: cmake --build build -j4

      - name: run
        run: ./build/app/AFRODITE -m macros/run.mac

      - name: test
        run: |
          cd build
          ctest --build-config Debug