name: MacOS

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  CTEST_OUTPUT_ON_FAILURE: 1
  CPM_SOURCE_CACHE: ${{ github.workspace }}/cpm_modules

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Update Homebrew
        run: |
          brew tap vetlewi/formula
          brew update --preinstall
          cat "$(brew --repository)/Library/Taps/vetlewi/homebrew-formula/geant4.rb" > .github/brew-formulae

      - name: Configure Homebrew cache
        uses: actions/cache@v2
        with:
          path: |
            ~/Library/Cache/Homebrew/geant4--*
            ~/Library/Cache/homebrew/downloads/*--geant4-*
            ~/Library/Cache/Homebrew/downloads/*--G4*
          key: brew-${{ hashFiles('.github/brew-formulae') }}

      - name: Install Homebrew dependencies
        run: brew install assimp

      - name: Installing Geant4
        run: brew install --force-bottle geant4

      - uses: actions/cache@v2
        with:
          path: "**/cpm_modules"
          key: ${{ github.workflow }}-cpm-modules-${{ hashFiles('**/CMakeLists.txt', '**/*.cmake') }}

      - name: configure
        run: cmake -Sall -Bbuild -DCMAKE_BUILD_TYPE=Debug

      - name: build
        run: cmake --build build -j4

      - name: run
        run: |
          . /usr/local/bin/geant4.sh
          env
          ./build/app/AFRODITE -m macros/run.mac

      - name: test
        run: |
          cd build
          ctest --build-config Debug