name: Standalone

on:
  #push:
  #  branches:
  #    - master
  #pull_request:
  #  branches:
  #    - master

env:
  CPM_SOURCE_CACHE: ${{ github.workspace }}/cpm_modules

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Install Geant4 dependencies
        run: |
          sudo apt install -qq libtbb-dev libassimp-dev libxmu-dev
          sudo brew tap vetlewi/formula

      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: "**/cpm_modules"
          key: ${{ github.workflow }}-cpm-modules-${{ hashFiles('**/CMakeLists.txt', '**/*.cmake') }}

      - name: configure
        run: |
          source /usr/bin/geant4.sh
          cmake -Sapp -Bbuild -DCMAKE_BUILD_TYPE=Debug

      - name: build
        run: |
          source /usr/bin/geant4.sh
          cmake --build build -j4

      #- name: run
      #  run: ./build/app/AFRODITE