name: Standalone

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  CPM_SOURCE_CACHE: ${{ github.workspace }}/cpm_modules

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Install Geant4 dependencies
        run: sudo apt install -qq libtbb-dev libassimp-dev libxmu-dev libexpat-dev libxerces-c-dev qt5-default

      - name: Download Geant4
        run: |
          wget https://github.com/vetlewi/homebrew-formula/releases/download/v1.0/Geant4-10.7.1-Linux.sh
          chmod +x Geant4-10.7.1-Linux.sh

      - name: Install Geant4
        run: sudo ./Geant4-10.7.1-Linux.sh --skip-license --prefix=/usr

      - name: Download and install G4EMLOW
        run: |
          wget https://cern.ch/geant4-data/datasets/G4EMLOW.7.13.tar.gz
          tar xvf G4EMLOW.7.13.tar.gz
          sudo mkdir /usr/share/Geant4-10.7.1/data
          mv G4EMLOW.7.13 /usr/share/Geant4-10.7.1/data


      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: "**/cpm_modules"
          key: ${{ github.workflow }}-cpm-modules-${{ hashFiles('**/CMakeLists.txt', '**/*.cmake') }}

      - name: configure
        run: |
          source /usr/bin/geant4.sh
          cmake -Sapp -Bbuild -DCMAKE_BUILD_TYPE=Debug

      - name: build
        run: |
          source /usr/bin/geant4.sh
          cmake --build build -j4

      - name: run
        run: ./build/app/AFRODITE -m macros/run.mac