name: Style

on: workflow_dispatch

env:
  CPM_SOURCE_CACHE: ${{ github.workspace }}/cpm_modules

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: "**/cpm_modules"
          key: ${{ github.workflow }}-cpm-modules-${{ hashFiles('**/CMakeLists.txt', '**/*.cmake') }}

      - name: Update Homebrew
        run: |
          brew tap vetlewi/formula
          brew update --preinstall
          cat "$(brew --repository)/Library/Taps/vetlewi/homebrew-formula/geant4.rb" > .github/brew-formulae

      - name: Configure Homebrew cache
        uses: actions/cache@v2
        with:
          path: |
            ~/Library/Cache/Homebrew/geant4--*
            ~/Library/Cache/homebrew/downloads/*--geant4-*
            ~/Library/Cache/Homebrew/downloads/*--G4*
          key: brew-${{ hashFiles('.github/brew-formulae') }}

      - name: Install Homebrew dependencies
        run: brew install assimp qt@5 expat xerces-c

      - name: Installing Geant4
        run: brew install --force-bottle geant4

      - name: Install format dependencies
        run: |
          brew install clang-format
          pip3 install cmake_format==0.6.11 pyyaml
      - name: configure
        run: cmake -Stest -Bbuild

      - name: check style
        run: cmake --build build --target check-format